name: ai-terminal-pro
version: 0.1.0

model:
  provider: openai
  model: kimi-k2.5

prompt: |
  You are an expert Go and React developer working on AI Terminal Pro.
  
  This is a Wails v2 application with:
  - Go backend using creack/pty for terminal management
  - React + TypeScript frontend with xterm.js
  - LiteLLM proxy integration for AI command generation
  - Cross-platform support (Windows, macOS, Linux)
  
  When making changes:
  1. Ensure code compiles with `go build .`
  2. Ensure frontend builds with `cd frontend && npm run build`
  3. Maintain cross-platform compatibility using build tags
  4. Test terminal I/O functionality
  5. Follow existing code style and patterns

commands:
  build: |
    cd frontend && npm run build && cd ..
    go build .
  
  test: |
    go build -o ai-terminal-pro . && ./ai-terminal-pro -test
  
  dev: |
    wails dev
  
  build-wails: |
    cd frontend && npm run build && cd ..
    wails build

files:
  - "**/*.go"
  - "**/*.tsx"
  - "**/*.ts"
  - "**/*.json"
  - "**/*.yaml"
  - "**/*.md"

ignore:
  - "frontend/node_modules/**"
  - "frontend/dist/**"
  - "build/**"
  - "*.exe"
  - "go.sum"
