// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GenerateCommand(arg1:string):Promise<Record<string, any>>;

export function GetOS():Promise<string>;

export function GetSettings():Promise<config.Settings>;

export function GetShell():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ReadFromTerminal():Promise<string>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function ValidateCommand(arg1:string):Promise<Record<string, any>>;

export function WriteToTerminal(arg1:string):Promise<void>;
