// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateCommand(arg1) {
  return window['go']['main']['App']['GenerateCommand'](arg1);
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetShell() {
  return window['go']['main']['App']['GetShell']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadFromTerminal() {
  return window['go']['main']['App']['ReadFromTerminal']();
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ValidateCommand(arg1) {
  return window['go']['main']['App']['ValidateCommand'](arg1);
}

export function WriteToTerminal(arg1) {
  return window['go']['main']['App']['WriteToTerminal'](arg1);
}
